### PR TITLE
Separate out base integration logic from spock

### PR DESCRIPTION
**Pull request by dansanduleac**
## Before this PR

`IntegrationSpec` and `IntegrationTestKitSpec` provide a lot of nice logic but are inextricably tied to `spock.lang.Specification`, which is tied to a specific Junit 4 runner.
This means that it's very hard to run these tests with a different testing engine, such as junit-jupiter (aka Junit 5).

## After this PR

Common logic that is testing engine agnostic is pulled out into three traits:
* Integration <: IntegrationBase
* IntegrationBase
* IntegrationTestKitBase

Such that they can be extended to provide support for Junit 5 or other testing engines.

### CODE REVIEW

**Comment by dansanduleac** [comment]
@rpalcolea do you have any thoughts on this approach?
We'd like to migrate to running gradle integration tests in Junit 5 (can run them in parallel) but are currently blocked by this.

**Comment by rpalcolea** [comment]
Hey @dansanduleac , mind updating your branch with master? we will take a look at it Today

**Comment by dansanduleac** [comment]
@rpalcolea updated.
Please let me know what you think of the approach.
I could also add junit 5 variants directly if you prefer that, as that's the main reason for setting it up this way.

FWIW, I've experimented with this locally and ran into another problem, which is that Gradle TestKit gets a bit confused when running multiple tests in parallel, even if I give them different test kit dirs, so there's a bit more work I need to do to try to figure that out.

**Comment by dansanduleac** [comment]
@rpalcolea ping again?

**Pull request merged**
